### PR TITLE
Enhancement: Keep packages sorted in composer.json

### PR DESCRIPTION
**Pull request by localheinz**
This PR

* [x] keeps packages sorted in `composer.json`

### CODE REVIEW

**Comment by DonCallisto** [comment]
LGTM but we should improve this with some automated tool like php-cs or something like this.
Of course is not strictly related to this PR but we should consider it.

**Comment by DonCallisto** [comment]
Yes!

**Comment by jakzal** [comment]
Thank you! 🍺

**Comment by localheinz** [comment]
Thank you, @DonCallisto and @jakzal!

**Pull request merged**
