### PR TITLE
Enhancement: Normalize composer.json

### PR DESCRIPTION
**Pull request by localheinz**
This PR

* [x] normalizes `composer.json`

💁‍♂️ I ran

```
$ composer global require localheinz/composer-normalize:^1.0.0
```

followed by

```
$ composer normalize
```

For reference, also see https://github.com/localheinz/composer-normalize.

### CODE REVIEW

**Comment by jakzal** [comment]
Cheers 🍺

**Comment by DonCallisto** [comment]
Shouldn’t this be integrated into Travis?

**Comment by localheinz** [comment]
Thank you, @jakzal!

**Comment by localheinz** [comment]
@DonCallisto 

> Shouldn’t this be integrated into Travis?

Requires PHP 7.1. Happy to integrate when the requirement here is updated. 👍

**Pull request merged**
